apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-mongodb-setup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: mongo-setup
        image: mongo:5.0
        env:
          - name: MONGO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: root-username
          - name: MONGO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: root-password
          - name: MONGO_APP_USER
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: app-username
          - name: MONGO_APP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: app-password
        command:
        - /bin/bash
        - -c
        - |
          mongo --host mongodb -u "$MONGO_ROOT_USER" -p "$MONGO_ROOT_PASSWORD" --authenticationDatabase admin sausage-store --eval "
            if (db.getUser(\"$MONGO_APP_USER\") == null) {
              db.createUser({user: \"$MONGO_APP_USER\", pwd: \"$MONGO_APP_PASSWORD\", roles: [{ role: \"readWrite\", db: \"sausage-store\" }]});
              print(\"user created\");
            } else {
              db.updateUser(\"$MONGO_APP_USER\", {pwd: \"$MONGO_APP_PASSWORD\", roles: [{ role: \"readWrite\", db: \"sausage-store\" }]});
              print(\"user already exists, updated\");
            }
          "
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "250m"
      restartPolicy: OnFailure
