{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
data:
  root-username: {{ required "mongodb.env.MONGO_INITDB_ROOT_USERNAME is required" .Values.mongodb.env.MONGO_INITDB_ROOT_USERNAME | b64enc | quote }}
  root-password: {{ required "mongodb.env.MONGO_INITDB_ROOT_PASSWORD is required" .Values.mongodb.env.MONGO_INITDB_ROOT_PASSWORD | b64enc | quote }}
  app-username: {{ required "mongodb.env.MONGO_APP_USERNAME is required" .Values.mongodb.env.MONGO_APP_USERNAME | b64enc | quote }}
  app-password: {{ required "mongodb.env.MONGO_APP_PASSWORD is required" .Values.mongodb.env.MONGO_APP_PASSWORD | b64enc | quote }}
{{- end }}
