{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
data:
  root-password: {{ default "" .Values.mongodb.env.MONGO_INITDB_ROOT_PASSWORD | b64enc | quote }}
{{- end }}
