postgresql:
  enabled: true
  image: postgres:14-alpine
  containerPort: 5432
  service:
    name: postgresql
    port: 5432
  persistence:
    size: 3Gi
  env:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgrespassword
    STORE_DATABASE: sausage_store
    STORE_USER: store
    STORE_PASSWORD: storepassword
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

mongodb:
  enabled: true
  image: mongo:7.0
  env:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: rootpassword
    MONGO_APP_USERNAME: reports
    MONGO_APP_PASSWORD: reportspassword
  containerPort: 27017