global:
  imagePullPolicy: Always
  vault:
    host: ""
    name: vault

frontend:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: "<YOUR_HOSTNAME>.students-projects.ru"
    path: /
    pathType: Prefix
  containerPort: 80
  image: "YOUR_DOCKERHUB/sausage-frontend:latest"
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgresql:5432/sausage_store
    reportPath: /logs/reports
    logPath: /logs
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  image: "YOUR_DOCKERHUB/sausage-backend:latest"
  imagePullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "1"
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
  vpa:
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: '*'
          minAllowed:
            cpu: 100m
            memory: 256Mi
          maxAllowed:
            cpu: 1
            memory: 512Mi

backend-report:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  image: "YOUR_DOCKERHUB/sausage-backend-report:latest"
  containerPort: 8080
  service:
    port: 8080
  env:
    port: "8080"
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80